name: CI # Continuous Integration

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-22.04, windows-2022]

        name: ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        steps:
            -   uses: actions/checkout@v4

            -   uses: xmake-io/github-action-setup-xmake@v1
                with:
                    xmake-version: latest

            -   uses: Jimver/cuda-toolkit@v0.2.19
                id: cuda-toolkit
                with:
                    log-file-suffix: ${{ matrix.os }}.txt
                    cuda: '12.5.0'
                    method: 'network'
                    sub-packages: '["nvcc", "cudart", "cublas"]'

            -   name: Build
                run: make build

            -   name: Test
                run: |
                    make run
                    make test
